### ISSUE TITLE
unresolved module, can't find module file: create_raydium_pool.rs, or create_raydium_pool/mod.rs

### ISSUE THREAD

**Issue by Red-T007** [0xapp123/Pumpfun-Smart-Contract#7]
Cant' find create_raydium_pool module in the /programs/pump/src/instructions

**Comment by 0xapp123** [comment]
I removed it on my side,
If you want it, I can provide personally!
Plz contact on other chatting apps

**Comment by Red-T007** [comment]
where I can contact with you

**Comment by 0xapp123** [comment]
Telegram @Tr1030109 Discord 0xapp123

**Comment by Red-T007** [comment]
I sent a friend request to your Discord
